name: Lint with Flake8,black
# Uses: https://github.com/marketplace/actions/flake8-annotator
# Uses: https://black.readthedocs.io/en/stable/integrations/github_actions.html
# Ref: https://buildersbox.corp-sansan.com/entry/2021/02/18/110000
# Ref: https://black.readthedocs.io/en/stable/index.html

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
      
    - name: Setup black_check
      uses: psf/black@stable
      
    - name: Formatter
      uses: black . --line-length=100 --diff
