name: Formatter with black
# Uses: https://github.com/marketplace/actions/black-check
# Ref: https://black.readthedocs.io/en/stable/index.html

on:
  pull_request:
    types:
      - opened
    paths:
      - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Setup black_check
        uses: jpetrucciani/black-check@master

      - name: Formatter with black
        run: |
          black . --line-length=100 --diff
