name: Code formatter with black

on:
  push:
    paths:
    - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Setup black_check
        uses: jpetrucciani/black-check@master

      - name: Lint with black
        run: |
          black . --line-length=88 --diff
