name: Lint with Flake8
# Uses: https://github.com/marketplace/actions/flake8-annotator
# Ref: https://buildersbox.corp-sansan.com/entry/2021/02/18/110000

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Setup GitHub annotations
      uses: rbialon/flake8-annotations@v1

    - name: Lint with flake8
      run: |
        FLAKE8_OUT=$(flake8 . --count --select=E9,F63,F7,F82 --show-source --exit-zero --max-complexity=10 --ignore E402,E722,E302,W503 --max-line-length=100 --statistics)
        echo "$FLAKE8_OUT"
        
        FLAKE8_ERRORS=$(echo "$FLAKE8_OUT" | grep -P '^.+:\d+:\d+:\s*E' || true)
        if [ -n "$FLAKE8_ERRORS" ]; then
          echo "::error::!!flake8 errors detected!!"
          exit 1
        fi
